# Obiettivo Scrivere un programma in Python che genera un nome per 
# una band musicale utilizzando due input forniti dall'utente: 
# la città di origine e il nome del proprio animale domestico.

city_name = input("la tua citta' di origine > ")
pet_name = input("il nome del tuo animale domestico > ")
band_name = city_name + " " + pet_name

print(f"il nome della tua band e': '{band_name}'\n...\n...\nIl successo e' assicurato!")
